# Generated by Django 4.1.2 on 2022-11-04 07:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Experiences",
            new_name="Experience",
        ),
    ]
